-- Keyword database + full five-state targeting for the lead scrapers.
--
-- 1. Adds NY to the live scraping regions (target set: NJ, PA, NY, MD, VA).
-- 2. Creates public.lead_keywords — the editable keyword database the scrapers
--    read at run time, seeded for ShieldTech's trades: network infrastructure,
--    structured cabling, fire alarm, AV, access control, CCTV/video
--    surveillance, and burglar/security alarms.
-- 3. Registers additional bid platforms (BidNet state pages, NYC City Record,
--    NY OGS, Port Authority NY/NJ) so leads pull from public portals whether or
--    not SAM.gov is configured.

-- ── 1. Regions: add NY, and make it the default for fresh installs ──────────
alter table public.lead_config alter column regions set default '{NJ,PA,NY,MD,VA}';
update public.lead_config set regions = array_append(regions, 'NY')
  where id = 1 and not ('NY' = any(regions));

-- ── 2. Keyword database ─────────────────────────────────────────────────────
create table if not exists public.lead_keywords (
  id         bigint generated always as identity primary key,
  category   text not null,          -- trade bucket, e.g. 'cctv', 'fire-alarm'
  keyword    text not null,
  enabled    boolean not null default true,
  created_at timestamptz not null default now(),
  unique (category, keyword)
);

alter table public.lead_keywords enable row level security;

create policy "lead_keywords: read" on public.lead_keywords
  for select using (auth.uid() is not null);
create policy "lead_keywords: write" on public.lead_keywords
  for all using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('Admin','Staff'))
  );

insert into public.lead_keywords (category, keyword) values
  -- Network infrastructure
  ('network-infrastructure', 'network infrastructure'),
  ('network-infrastructure', 'network upgrade'),
  ('network-infrastructure', 'network equipment'),
  ('network-infrastructure', 'network installation'),
  ('network-infrastructure', 'LAN'),
  ('network-infrastructure', 'WAN'),
  ('network-infrastructure', 'wireless network'),
  ('network-infrastructure', 'wireless access point'),
  ('network-infrastructure', 'Wi-Fi'),
  ('network-infrastructure', 'WLAN'),
  ('network-infrastructure', 'network switch'),
  ('network-infrastructure', 'router'),
  ('network-infrastructure', 'firewall'),
  ('network-infrastructure', 'IT infrastructure'),
  ('network-infrastructure', 'data center'),
  ('network-infrastructure', 'server room'),
  ('network-infrastructure', 'MDF'),
  ('network-infrastructure', 'IDF'),
  ('network-infrastructure', 'telecommunications'),
  ('network-infrastructure', 'telecom infrastructure'),
  ('network-infrastructure', 'VoIP'),
  ('network-infrastructure', 'voice over IP'),
  ('network-infrastructure', 'unified communications'),
  ('network-infrastructure', 'broadband'),
  ('network-infrastructure', 'ethernet'),
  ('network-infrastructure', 'fiber network'),
  ('network-infrastructure', 'network refresh'),
  ('network-infrastructure', 'network modernization'),
  -- Structured cabling
  ('structured-cabling', 'structured cabling'),
  ('structured-cabling', 'low voltage cabling'),
  ('structured-cabling', 'low-voltage wiring'),
  ('structured-cabling', 'data cabling'),
  ('structured-cabling', 'voice and data'),
  ('structured-cabling', 'Cat5e'),
  ('structured-cabling', 'Cat6'),
  ('structured-cabling', 'Cat6A'),
  ('structured-cabling', 'category 6'),
  ('structured-cabling', 'fiber optic'),
  ('structured-cabling', 'fiber optic cabling'),
  ('structured-cabling', 'fiber installation'),
  ('structured-cabling', 'copper cabling'),
  ('structured-cabling', 'cable plant'),
  ('structured-cabling', 'horizontal cabling'),
  ('structured-cabling', 'backbone cabling'),
  ('structured-cabling', 'riser cabling'),
  ('structured-cabling', 'patch panel'),
  ('structured-cabling', 'telecommunications room'),
  ('structured-cabling', 'telecom closet'),
  ('structured-cabling', 'cable tray'),
  ('structured-cabling', 'conduit and cabling'),
  ('structured-cabling', 'BICSI'),
  ('structured-cabling', 'RCDD'),
  ('structured-cabling', 'communications cabling'),
  ('structured-cabling', 'premise wiring'),
  -- Fire alarm & life safety
  ('fire-alarm', 'fire alarm'),
  ('fire-alarm', 'fire alarm system'),
  ('fire-alarm', 'fire alarm replacement'),
  ('fire-alarm', 'fire alarm upgrade'),
  ('fire-alarm', 'fire detection'),
  ('fire-alarm', 'fire notification'),
  ('fire-alarm', 'smoke detector'),
  ('fire-alarm', 'smoke detection'),
  ('fire-alarm', 'fire panel'),
  ('fire-alarm', 'FACP'),
  ('fire-alarm', 'NFPA 72'),
  ('fire-alarm', 'sprinkler monitoring'),
  ('fire-alarm', 'fire suppression monitoring'),
  ('fire-alarm', 'carbon monoxide detection'),
  ('fire-alarm', 'mass notification'),
  ('fire-alarm', 'emergency communication system'),
  ('fire-alarm', 'voice evacuation'),
  ('fire-alarm', 'emergency notification'),
  ('fire-alarm', 'life safety system'),
  ('fire-alarm', 'fire safety system'),
  -- Audio/visual
  ('av', 'audiovisual'),
  ('av', 'audio visual'),
  ('av', 'audio-visual'),
  ('av', 'AV system'),
  ('av', 'A/V system'),
  ('av', 'sound system'),
  ('av', 'sound reinforcement'),
  ('av', 'public address'),
  ('av', 'PA system'),
  ('av', 'paging system'),
  ('av', 'intercom'),
  ('av', 'intercom system'),
  ('av', 'distributed audio'),
  ('av', 'video wall'),
  ('av', 'digital signage'),
  ('av', 'projector'),
  ('av', 'projection system'),
  ('av', 'videoconferencing'),
  ('av', 'video conferencing'),
  ('av', 'conference room technology'),
  ('av', 'classroom technology'),
  ('av', 'classroom audio'),
  ('av', 'auditorium sound'),
  ('av', 'gymnasium sound'),
  ('av', 'assistive listening'),
  ('av', 'hearing assistance system'),
  ('av', 'bell and clock system'),
  -- Access control
  ('access-control', 'access control'),
  ('access-control', 'access control system'),
  ('access-control', 'card access'),
  ('access-control', 'card reader'),
  ('access-control', 'badge access'),
  ('access-control', 'badging system'),
  ('access-control', 'keyless entry'),
  ('access-control', 'electronic locks'),
  ('access-control', 'electrified door hardware'),
  ('access-control', 'electric strike'),
  ('access-control', 'magnetic lock'),
  ('access-control', 'maglock'),
  ('access-control', 'proximity reader'),
  ('access-control', 'credential reader'),
  ('access-control', 'biometric access'),
  ('access-control', 'turnstile'),
  ('access-control', 'door entry system'),
  ('access-control', 'entry control'),
  ('access-control', 'visitor management'),
  ('access-control', 'door access'),
  ('access-control', 'security door'),
  ('access-control', 'gate operator'),
  ('access-control', 'gate access'),
  -- CCTV / video surveillance
  ('cctv', 'CCTV'),
  ('cctv', 'closed circuit television'),
  ('cctv', 'video surveillance'),
  ('cctv', 'surveillance system'),
  ('cctv', 'surveillance camera'),
  ('cctv', 'security camera'),
  ('cctv', 'security cameras'),
  ('cctv', 'IP camera'),
  ('cctv', 'camera system'),
  ('cctv', 'camera installation'),
  ('cctv', 'camera upgrade'),
  ('cctv', 'video management system'),
  ('cctv', 'VMS'),
  ('cctv', 'NVR'),
  ('cctv', 'DVR'),
  ('cctv', 'video recorder'),
  ('cctv', 'video analytics'),
  ('cctv', 'license plate recognition'),
  ('cctv', 'LPR'),
  ('cctv', 'ANPR'),
  ('cctv', 'PTZ camera'),
  ('cctv', 'video monitoring'),
  -- Burglar / intrusion & security alarms
  ('intrusion-alarm', 'burglar alarm'),
  ('intrusion-alarm', 'burglary alarm'),
  ('intrusion-alarm', 'intrusion alarm'),
  ('intrusion-alarm', 'intrusion detection'),
  ('intrusion-alarm', 'security alarm'),
  ('intrusion-alarm', 'alarm system'),
  ('intrusion-alarm', 'alarm monitoring'),
  ('intrusion-alarm', 'alarm installation'),
  ('intrusion-alarm', 'motion detector'),
  ('intrusion-alarm', 'motion sensor'),
  ('intrusion-alarm', 'glass break detection'),
  ('intrusion-alarm', 'door contact'),
  ('intrusion-alarm', 'panic alarm'),
  ('intrusion-alarm', 'panic button'),
  ('intrusion-alarm', 'duress alarm'),
  ('intrusion-alarm', 'holdup alarm'),
  ('intrusion-alarm', 'perimeter security'),
  ('intrusion-alarm', 'perimeter intrusion detection'),
  ('intrusion-alarm', 'central station monitoring'),
  ('intrusion-alarm', 'UL monitoring'),
  -- General security / low-voltage catch-alls
  ('general-security', 'security system'),
  ('general-security', 'security systems integration'),
  ('general-security', 'physical security'),
  ('general-security', 'electronic security'),
  ('general-security', 'electronic safety and security'),
  ('general-security', 'security upgrades'),
  ('general-security', 'security improvements'),
  ('general-security', 'security enhancements'),
  ('general-security', 'security equipment'),
  ('general-security', 'security integrator'),
  ('general-security', 'security installation'),
  ('general-security', 'school security'),
  ('general-security', 'school safety'),
  ('general-security', 'campus security'),
  ('general-security', 'building security'),
  ('general-security', 'facility security'),
  ('general-security', 'low voltage'),
  ('general-security', 'low-voltage electrical'),
  ('general-security', 'Division 27'),
  ('general-security', 'Division 28'),
  ('general-security', 'communications systems'),
  ('general-security', 'special systems'),
  ('general-security', 'technology systems')
on conflict (category, keyword) do nothing;

-- ── 3. More bid platforms (five-state coverage, SAM.gov-independent) ────────
insert into public.sources (id, name, url, kind, has_api, lane, listing_url) values
  -- BidNet Direct per-state aggregator pages (static listing pages)
  ('bidnet-nj', 'BidNet Direct — New Jersey', 'https://www.bidnetdirect.com', 'portal', false, 'bid',
     'https://www.bidnetdirect.com/new-jersey'),
  ('bidnet-pa', 'BidNet Direct — Pennsylvania', 'https://www.bidnetdirect.com', 'portal', false, 'bid',
     'https://www.bidnetdirect.com/pennsylvania'),
  ('bidnet-ny', 'BidNet Direct — New York', 'https://www.bidnetdirect.com', 'portal', false, 'bid',
     'https://www.bidnetdirect.com/new-york'),
  ('bidnet-md', 'BidNet Direct — Maryland', 'https://www.bidnetdirect.com', 'portal', false, 'bid',
     'https://www.bidnetdirect.com/maryland'),
  ('bidnet-va', 'BidNet Direct — Virginia', 'https://www.bidnetdirect.com', 'portal', false, 'bid',
     'https://www.bidnetdirect.com/virginia'),
  -- New York
  ('ny-ogs', 'NY OGS — Bid Opportunities', 'https://ogs.ny.gov', 'portal', false, 'bid',
     'https://ogs.ny.gov/procurement/bid-opportunities'),
  ('ny-cityrecord', 'NYC City Record Online — Procurement Notices', 'https://a856-cityrecord.nyc.gov', 'portal', false, 'bid',
     'https://a856-cityrecord.nyc.gov/Search?NoticeTypeId=2'),
  ('panynj', 'Port Authority NY/NJ — Solicitations', 'https://www.panynj.gov', 'portal', false, 'bid',
     'https://www.panynj.gov/port-authority/en/business-opportunities/solicitations-advertisements.html')
on conflict (id) do update set
  name = excluded.name, url = excluded.url, kind = excluded.kind,
  lane = excluded.lane, listing_url = excluded.listing_url;
