-- Keyword database expansion — full coverage of ShieldTech's low-voltage
-- service lines: CCTV, access control, fire, burg/intrusion alarms, A/V, and
-- Cat/structured cabling (plus network + general security). Adds deeper trade
-- vocabulary, spec-sheet language, and the manufacturer names that appear in
-- public solicitations. Same table, additive + idempotent.

insert into public.lead_keywords (category, keyword) values
  -- CCTV / video surveillance
  ('cctv', 'camera replacement'),
  ('cctv', 'video security'),
  ('cctv', 'surveillance upgrade'),
  ('cctv', 'CCTV maintenance'),
  ('cctv', 'dome camera'),
  ('cctv', 'bullet camera'),
  ('cctv', 'multisensor camera'),
  ('cctv', 'thermal camera'),
  ('cctv', 'thermal imaging'),
  ('cctv', 'IP video'),
  ('cctv', 'megapixel camera'),
  ('cctv', 'video storage'),
  ('cctv', 'video server'),
  ('cctv', 'cloud video'),
  ('cctv', 'Axis camera'),
  ('cctv', 'Hanwha'),
  ('cctv', 'Avigilon'),
  ('cctv', 'Verkada'),
  ('cctv', 'Milestone VMS'),
  ('cctv', 'Genetec'),
  ('cctv', 'exacqVision'),
  ('cctv', 'Pelco'),
  ('cctv', 'Bosch camera'),
  -- Access control
  ('access-control', 'door controller'),
  ('access-control', 'access panel'),
  ('access-control', 'key fob'),
  ('access-control', 'keycard'),
  ('access-control', 'mobile credential'),
  ('access-control', 'wireless locks'),
  ('access-control', 'request to exit'),
  ('access-control', 'door position switch'),
  ('access-control', 'delayed egress'),
  ('access-control', 'door alarm'),
  ('access-control', 'mantrap'),
  ('access-control', 'video intercom'),
  ('access-control', 'door station'),
  ('access-control', 'telephone entry'),
  ('access-control', 'Lenel'),
  ('access-control', 'CCURE'),
  ('access-control', 'Software House'),
  ('access-control', 'AMAG'),
  ('access-control', 'Brivo'),
  ('access-control', 'Openpath'),
  ('access-control', 'Avigilon Alta'),
  ('access-control', 'HID reader'),
  ('access-control', 'Salto'),
  ('access-control', 'Allegion'),
  ('access-control', 'Von Duprin'),
  ('access-control', 'Mercury controller'),
  -- Fire alarm & life safety
  ('fire-alarm', 'addressable fire alarm'),
  ('fire-alarm', 'fire alarm inspection'),
  ('fire-alarm', 'fire alarm testing'),
  ('fire-alarm', 'fire alarm monitoring'),
  ('fire-alarm', 'fire alarm service'),
  ('fire-alarm', 'pull station'),
  ('fire-alarm', 'horn strobe'),
  ('fire-alarm', 'notification appliance'),
  ('fire-alarm', 'annunciator'),
  ('fire-alarm', 'duct detector'),
  ('fire-alarm', 'heat detector'),
  ('fire-alarm', 'beam detector'),
  ('fire-alarm', 'CO detector'),
  ('fire-alarm', 'fire protection system'),
  ('fire-alarm', 'Notifier'),
  ('fire-alarm', 'Simplex'),
  ('fire-alarm', 'SimplexGrinnell'),
  ('fire-alarm', 'Fire-Lite'),
  ('fire-alarm', 'Silent Knight'),
  ('fire-alarm', 'Edwards EST'),
  ('fire-alarm', 'Siemens fire'),
  ('fire-alarm', 'Honeywell fire'),
  -- Burglar / intrusion alarms
  ('intrusion-alarm', 'alarm panel'),
  ('intrusion-alarm', 'alarm keypad'),
  ('intrusion-alarm', 'alarm upgrade'),
  ('intrusion-alarm', 'alarm replacement'),
  ('intrusion-alarm', 'alarm service'),
  ('intrusion-alarm', 'alarm inspection'),
  ('intrusion-alarm', '24-hour monitoring'),
  ('intrusion-alarm', 'intrusion panel'),
  ('intrusion-alarm', 'silent alarm'),
  ('intrusion-alarm', 'hold-up alarm'),
  ('intrusion-alarm', 'door prop alarm'),
  ('intrusion-alarm', 'DSC panel'),
  ('intrusion-alarm', 'DMP'),
  ('intrusion-alarm', 'Honeywell Vista'),
  ('intrusion-alarm', 'Bosch intrusion'),
  -- Audio / visual
  ('av', 'AV integration'),
  ('av', 'commercial audio'),
  ('av', 'background music'),
  ('av', 'speaker installation'),
  ('av', 'loudspeaker'),
  ('av', 'amplifier'),
  ('av', 'microphone system'),
  ('av', 'audio DSP'),
  ('av', 'AV over IP'),
  ('av', 'video distribution'),
  ('av', 'interactive display'),
  ('av', 'interactive whiteboard'),
  ('av', 'LED display'),
  ('av', 'LED video wall'),
  ('av', 'smart classroom'),
  ('av', 'lecture capture'),
  ('av', 'Crestron'),
  ('av', 'Extron'),
  ('av', 'AMX'),
  ('av', 'Biamp'),
  ('av', 'QSC'),
  ('av', 'Shure'),
  -- Cat / structured cabling
  ('structured-cabling', 'Cat5'),
  ('structured-cabling', 'Cat7'),
  ('structured-cabling', 'category 5e'),
  ('structured-cabling', 'category 6a'),
  ('structured-cabling', 'network cabling'),
  ('structured-cabling', 'cable installation'),
  ('structured-cabling', 'cabling contractor'),
  ('structured-cabling', 'voice cabling'),
  ('structured-cabling', 'data drops'),
  ('structured-cabling', 'network drops'),
  ('structured-cabling', 'cable pathways'),
  ('structured-cabling', 'fiber splicing'),
  ('structured-cabling', 'fiber backbone'),
  ('structured-cabling', 'single mode fiber'),
  ('structured-cabling', 'multimode fiber'),
  ('structured-cabling', 'OTDR testing'),
  ('structured-cabling', 'cable certification'),
  ('structured-cabling', 'innerduct'),
  ('structured-cabling', 'telecommunications infrastructure'),
  -- Network infrastructure
  ('network-infrastructure', 'core switch'),
  ('network-infrastructure', 'PoE switch'),
  ('network-infrastructure', 'power over ethernet'),
  ('network-infrastructure', 'uninterruptible power supply'),
  ('network-infrastructure', 'wireless survey'),
  ('network-infrastructure', 'wireless bridge'),
  ('network-infrastructure', 'point to point wireless'),
  ('network-infrastructure', 'Cisco'),
  ('network-infrastructure', 'Aruba'),
  ('network-infrastructure', 'Meraki'),
  ('network-infrastructure', 'Ubiquiti'),
  ('network-infrastructure', 'UniFi'),
  -- General security / emergency systems
  ('general-security', 'security assessment'),
  ('general-security', 'risk assessment'),
  ('general-security', 'emergency phone'),
  ('general-security', 'blue light phone'),
  ('general-security', 'call box'),
  ('general-security', 'area of refuge'),
  ('general-security', 'nurse call'),
  ('general-security', 'duress system'),
  ('general-security', 'weapons detection'),
  ('general-security', 'metal detector'),
  ('general-security', 'gunshot detection'),
  ('general-security', 'vape detection'),
  ('general-security', 'parking gate'),
  ('general-security', 'barrier gate'),
  ('general-security', 'security bollards'),
  ('general-security', 'fence detection'),
  ('general-security', 'security camera grant'),
  ('general-security', 'electronic security systems')
on conflict (category, keyword) do nothing;
